name: Lint code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      - name: Set up Python 3.7
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # v2.2.2
        with:
          python-version: '3.7'
      - name: Install PyLint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run PyLint
        run: python -m pylint --errors-only twitch_clip_chat
